### ISSUE TITLE
VAT threshold 

### ISSUE THREAD

**Issue by YiffyToys** [gwharton/autocustomergroup#1]
"Import VAT Threshold - The order value (ex VAT) threshold (in Store Currency) above which no VAT should be charged. Calculated as the sum of all line items after discount ex Tax."

This does not work. It must match the HMRC regulations and not be some kind of estimate.
So it must be in GBP and use the HMRC currency exchange rate for the current month to convert from the shop currency to GBP.
(assuming the invoice is created in the same month)
Same goes for the required copies of all VAT related sums on the invoice in GBP in addition to the shop currency (of that currency is not GBP).

Exchange Rate
- HMRC Developer portal https://developer.service.hmrc.gov.uk/api-documentation/docs/api/xml/Exchange%20rates%20from%20HMRC
- API Implementation https://github.com/lukapeharda/hmrc-exchange-rates
(Yes, HMRC really calls a CSV download with a URL that changes every month an "API")

**Comment by YiffyToys** [comment]
Also don't forget "shipping and handling" fees as they are part of the value of a parcel.
All assuming there is only 1 shipment to fulfill the order that may consist of one or more boxes.

**Comment by gwharton** [comment]
ok, good feedback. At the moment, every month, the new exchange rate from HMRC could be used to manually convert to store currency and use that in the setting. I'll look at using the exchange rate api to automate this process so the setting would be in GBP and EUR, but for now, pick your exchange rates, make the conversion and put in store currency.

Invoicing is a whole other issue yet to be looked at!!! :)

**Comment by gwharton** [comment]
For the EU, the 150EUR threshold is the Intrinsic Value of the goods. The only definition I could find on what intrinsic value is defined as is 

"According to Dutch Customs the ‘intrinsic value’ is the value of the goods without costs such as transport,
insurance and mediation. I refer to: Belastingdienst Douane, ‘Handboek Douane – 24.2’
<www.belastingdienst.nl/bibliotheek/handboeken/html/boeken/HDU/douanevrijstellingen-begrippen.html#HDUd1e216922> accessed 15 January 2018."

I will check on the equivalent UK definition.

**Comment by YiffyToys** [comment]
Perfectly fine to get something working.
The shop keeper would do that after printing the last invoices for a month.
So it applies to all orders that have a tax-point in the next month. Doesn't have to be midnight.

PS:
I did some analysis for Invoices myself but I don't have enough UK customers at the moment to create an implemtation just yet (Just a plugin looking at the line itemsand add additional line items in GBP into the invoice.)

I did however get an answer from HMRC that just stating all EURO line items also in GBP using the official exchange rate would be fine for them. (Modifying the shipment manifest to create a GBP pro-forma invoice would not be.)

**Comment by gwharton** [comment]
And the UK definition of Intrinsic Value 

https://www.gov.uk/guidance/vat-and-overseas-goods-sold-directly-to-customers-in-the-uk

The seller must work out the consignment value of the goods by deciding their ‘intrinsic value’, this is the price the goods were sold for, not including:

- any transport or insurance costs, unless they are included in the price and not separately shown on the invoice
- any other identifiable taxes and charges

Unless sent individually, the seller must add the individual values of all items in a consignment together to get the total value of the consignment.

**Comment by gwharton** [comment]
Good point about multiple shipments. However this is done at the quote stage pre payment and you are unlikely to know how many boxes there will be at this stage. We generate customs invoices in magento separate from VAT invoices, and ours are generated based on the products in each shipment. Two shipments generates two customs invoices for us, with the shipping costs apportioned between the two. We allow multiple boxes per shipment too, but we only allow multiple boxes per tracking number, and ship a single customs invoice to cover both boxes covered under the same shipment, if that makes sense.

The case of a single order, over the threshold, being split into two shipments, shipped at different times, with each shipment below the threshold is just too much for my brain to cope with. I'll add it to the known issues.

I guess in this case, VAT would not be charged on the whole order, and when the individual items arrives at customs, they may take it to one side, add VAT plus a surcharge and ship to customer with a bill to pay. You can't really tell the customer, by the way, because I am going to split your parcel, you now have to pay me VAT.

**Comment by YiffyToys** [comment]
Don't fuzz about it. This would already solve 95% of the cases and it doesn't have to be perfect.

**Comment by gwharton** [comment]
Yeahh, aslong as the customs invoice is clear what has and what hasn't been charged, they can sort it out!!!

**Comment by gwharton** [comment]
Going to close this issue now.

Module has had a lot of work since this issue, particularly on Currencies and Exchange Rates.
